/*
 * FW.H
 *
 *  Created on: Jan 13, 2023
 *      Author: Noel Rojas Oliveras
 */

#ifndef __FRAMEWORK_FW_H__
#define __FRAMEWORK_FW_H__

/*************************
 * playstation libs
 *************************/
#include <libps.h>


/*************************
 * we shall call this framework oatmeal
 *************************/
#include "RENDER.H"
#include "PAD.H"
#include "OBJECT.H"
#include "CAMERA.H"
#include "AABB.H"

#endif /* FRAMEWORK_FW_H_ */
